version: "3.9"
services:
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - php-fpm